### ISSUE TITLE
In den Einkaufswagen hinzufügen

### ISSUE THREAD

**Issue by Serinoxu** [Projektarbeiten/ProjectPlatypus#39]
Wenn man nicht eingeloggt ist, erscheint ein fehler wenn man Produkte in den Einkaufswagen legen möchte

**Comment by Serinoxu** [comment]
dies passiert nur beim ersten mal drücken auf den Button, beim zweiten mal wurde es erfolgreich hinzugefügt

**Comment by GCoder002** [comment]
@Serinoxu das Problem hast du ja gelöst. Ich schließe mal den Issue für dich ;)
